#lancement tests sur api.py
---
name: run-tests-actions
run-name: tests by ${{ github.actor }} with pytest
on: [push]
jobs:
  run-tests-pytest:
    name: lancement tests pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    
    steps:
      - uses: actions/checkout@main
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test api with pytest
        run: |
          pip install pytest pytest-cov
          pytest test_api.py::test_accord_accorded --cov=api.py --cov-report=html
...