#lancement tests sur api.py
---
name: run-tests-actions
run-name: tests by ${{ github.actor }} with pytest
on: [push]
jobs:
  run-tests-pytest:
    name: lancement tests pytest
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        python-version: "3.10"
    
    steps:
      - uses: actions/checkout@main
      - name: Set up Python 3.10 #${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" #${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test api with pytest
        run: |
          pip install pytest pytest-cov
          pytest test_api.py 
...
#--cov=api.py --cov-report=html
